//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorWebForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional_Details
    {
        public int p_id { get; set; }
        public string School { get; set; }
        public string College { get; set; }
        public string University { get; set; }
        public string Experience { get; set; }
        public string U_id { get; set; }
    
        public virtual UserDetails UserDetails { get; set; }
    }
}
