//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorWebForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetails()
        {
            this.Professional_Details = new HashSet<Professional_Details>();
            this.Query_Post = new HashSet<Query_Post>();
            this.Query_Reply = new HashSet<Query_Reply>();
        }
    
        public string U_id { get; set; }
        public string U_name { get; set; }
        public string F_name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Phone_No { get; set; }
        public string Status { get; set; }
        public string Specailization { get; set; }
        public string u_Image { get; set; }
        public System.DateTime JoinedDate { get; set; }
        public string Nationality { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professional_Details> Professional_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Query_Post> Query_Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Query_Reply> Query_Reply { get; set; }
    }
}
